spring:
  application:
    name: techefx-spring-cloud-config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/techefx/environment-variable-repo.git

server:
  port: ${port:8888}

#pring.cloud.config.server.git.default-label=main