spring:
  application:
    name: techefx-property-access-service
  profiles:
    active: qa

server:
  port: ${port:8100}


management:
  endpoints:
    web:
      exposure:
        include: refresh

